# Generated by Django 2.2.6 on 2019-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagestext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='cover',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
